##############################################################
# Install PostgreSQL
##############################################################
- name: Add Postgres GPG key
  ansible.builtin.apt_key:
    url: '{{ postgres_gpg_key_url }}'
    state: present

- name: Add Postgres repo
  ansible.builtin.apt_repository:
    repo: '{{ postgres_repo }}'
    state: present

- name: Install Postgres 13
  apt:
    name: ['postgresql-13', 'postgresql-contrib', 'python3-pip', 'libpq-dev', 'acl']
    state: present

- name: Install Python package - psycopg2
  pip:
    name: 'psycopg2'

######################################################
# Setup Postgres database for Boundary
######################################################
- name: Create database for Boundary
  postgresql_db:
    name: '{{ postgres_dbname }}'
  become: yes
  become_method: sudo
  become_user: postgres

- name: Create user for Boundary
  postgresql_user:
    name: '{{ postgres_username }}'
    password: '{{ postgres_password }}'
    encrypted: 'yes'
  become: yes
  become_method: sudo
  become_user: postgres

- name: Grant boundary database user all privileges
  postgresql_privs:
    db: '{{ postgres_dbname }}'
    role: '{{ postgres_username }}'
    objs: ALL_IN_SCHEMA
    privs: ALL
  become: yes
  become_method: sudo
  become_user: postgres

- name: Enable pgcrypto extension
  postgresql_ext:
    name: pgcrypto
    db: '{{ postgres_dbname }}'
  become: yes
  become_method: sudo
  become_user: postgres

- name: Enable and restart Postgres
  service:
    name: 'postgresql'
    enabled: yes
    state: restarted
