####################################################################
# Install/Setup Fileabeat
####################################################################
# - name: Download Filebeat
#   win_get_url:
#     url: 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.0-windows-x86_64.zip'
#     dest: '%USERPROFILE%\AppData\Local\filebeat-7.5.0-windows-x86_64.zip'

# - name: Unzip filebeat
#   win_unzip:
#     src: '%USERPROFILE%\AppData\Local\filebeat-7.5.0-windows-x86_64.zip'
#     dest: '%USERPROFILE%\AppData\Local\filebeat'
#     creates: '%USERPROFILE%\AppData\Local\filebeat'


# - name: Copy Filebeat directory
#   win_copy:
#     src: '%USERPROFILE%\AppData\Local\filebeat\filebeat-{{ filebeat_version }}-windows-x86_64\'
#     dest: 'C:\Program Files\Filebeat'
#     remote_src: True

- name: Install Filebeat win_service
  win_shell: '.\install-service-filebeat.ps1'
  args:
    chdir: 'C:\Program Files\Filebeat'

- name: Copy filebeat.yml
  win_template:
    src: conf/windows-filebeat/filebeat.yml
    dest: 'C:\Program Files\Filebeat\filebeat.yml'

- name: Restart Filebeat
  win_service:
    name: filebeat
    state: restarted
    start_mode: auto


####################################################################
# Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting OSQuery agent on {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token is undefined
