################################################################
# Apt upgrade
################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
    force_apt_get: true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: true

- name: Disable kernel updates
  shell: 'apt-mark hold linux-image-generic linux-headers-generic'

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  timezone:
    name: '{{ timezone }}'

####################################################################
# Set hostname
####################################################################
- name: change hostname to {{ zeek_hostname }}
  hostname:
    name: "{{ zeek_hostname }}"

- name: add myself to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ zeek_hostname }}'
    state: present

####################################################################
# Install things
####################################################################
- name: Install things
  apt:
    name: ['apt-transport-https', 'openjdk-8-jre-headless', 'uuid-runtime', 'pwgen']
    state: latest
    force_apt_get: true
