################################################################
# Install prereqs
################################################################
- name: Install prereqs
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - 'cmake'
    - 'make'
    - 'gcc'
    - 'g++'
    - 'flex'
    - 'bison'
    - 'libpcap-dev'
    - 'libssl-dev'
    - 'python-dev'
    - 'swig'
    - 'zlib1g-dev'
    - 'libgeoip-dev'
    - 'build-essential'
    - 'libelf-dev'

################################################################
# Compile PF_RING
################################################################
- name: Git pull PF_RINT
  git:
    repo: '{{ pf_ring_url }}'
    dest: '{{ pf_ring_dir }}'

- name: PF_RING/kernel
  shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/kernel'
  with_items:
    - 'make'
    - 'insmod ./pf_ring.ko'
  ignore_errors: yes

- name: Make PF_RING/userland
  shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland'
  with_items:
    - 'make'

- name: Make PF_RING/userland/lib
  shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland/lib'
  with_items:
    - './configure --prefix={{ pf_ring_dir }}'
    - 'make install'

- name: Make PF_RING/userland/libpcap
  shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland//libpcap'
  with_items:
    - './configure --prefix={{ pf_ring_dir }}'
    - 'make install'

- name: Make PF_RING/userland/tcpdump
  shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland/tcpdump'
  with_items:
    - './configure --prefix={{ pf_ring_dir }}'
    - 'make install'

- name: Make PF_RING/kernel
  shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/kernel'
  with_items:
    - 'make'
    - 'make install'

################################################################
# Add pf_ring on boot
################################################################
- name: Add pf_ring on boot
  lineinfile:
    path: '/etc/modules'
    line: 'pf_ring'
    create: yes

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Compiled PF_RING - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token is undefined
