####################################################################
#  Setup Firewall
####################################################################
- name: Setup Ubuntu UFW firewall
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP for NGINX
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS for NGINX
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow Filebeat for Graylog
  ufw:
    rule: allow
    port: '{{ graylog_beats_port }}'
    proto: tcp
  when: graylog_beats_logging == True

- name: Allow Syslog TCP for Graylog
  ufw:
    rule: allow
    port: '{{ graylog_syslog_tcp_port }}'
    proto: tcp
  when: graylog_syslog_tcp_logging == True

- name: Allow Syslog UDP for Graylog
  ufw:
    rule: allow
    port: '{{ graylog_syslog_udp_port }}'
    proto: tcp
  when: graylog_syslog_udp_logging == True

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Setup UFW firewall - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token is undefined
