################################################################
# Install/Setup Graylog
################################################################
- name: Download Graylog repo
  get_url:
    url: '{{ graylog_repo_url }}'
    dest: '/tmp/graylog-repository_latest.deb'

- name: Install Graylog repo
  apt:
    deb: '/tmp/graylog-repository_latest.deb'

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install Graylog
  apt:
    name: 'graylog-server'
    state: latest

- name: Covert root_password_sha2
  shell: "echo -n {{ graylog_admin_password }} | sha256sum | awk '{print $1}'"
  register: pass_contents

- name: Set root_password_sha2
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^root_password_sha2 ='
    line: "root_password_sha2 = {{ pass_contents.stdout }}"

- name: Generate password_secret
  shell: "pwgen -s 96 1"
  register: secret_key_content

- name: Set password_secret
  shell: sed -i -e "s/password_secret =.*/password_secret = {{ secret_key_content.stdout }}/" /etc/graylog/server/server.conf

- name: Start Graylog service
  service:
    name: 'graylog-server'
    state: restarted
    enabled: yes

####################################################################
# Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: "{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Set up Graylog - {{ ansible_nodename }}"
    channel: "{{ slack_channel }}"
  when: slack_token is undefined
