#########################################################
# Get Kolide public certificate
#########################################################
- name:  Get Kolide public certificate
  community.crypto.get_certificate:
    host: "{{ kolide_hostname }}"
    port: "{{ kolide_port }}"
  run_once: true
  register: cert

- set_fact:
    kolide_public_cert: "{{ cert.cert }}"

#########################################################
# Get Osquery enroll secret from Kolide
#########################################################
- name: Get Osquery enrollment secret from Kolide
  uri:
    url: "https://{{ kolide_hostname }}:{{ kolide_port }}/api/v1/kolide/spec/enroll_secret"
    method: GET
    return_content: yes
    validate_certs: no
    headers:
      Authorization: "Bearer {{ lookup('env','KOLIDE_TOKEN') }}"
  register: enroll_secret

- set_fact:
    osquery_enroll_secret: "{{ enroll_secret.json.specs.secrets[0].secret }}"
