################################################################
# Install/Setup Filebeat
################################################################
- name: Install things
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - 'apt-transport-https'

- name: Add Filebeat key
  apt_key:
    url: '{{ filebeat_key }}'
    state: present

- name: Add Filebeat Repo
  apt_repository:
    repo: '{{ fileatbeat_repo_url }}'
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install filebeat
  apt:
    name: 'filebeat'
    state: latest

- name: Make backup of filebeat.yml
  copy:
    src: '/etc/filebeat/filebeat.yml'
    dest: '/etc/filebeat/filebeat.yml.bak'
    owner: root
    group: root
    mode: 0400
    remote_src: True

- name: Copy filebeat.yml
  template:
    src: 'conf/filebeat/filebeat.yml'
    dest: '/etc/filebeat/filebeat.yml'
    owner: root
    group: root
    mode: 0400

- name: Create Filebeat config directory
  file:
    path: '/etc/filebeat/conf.d'
    state: directory
    owner: root
    group: root
    mode: 0400

- name: Copy filebeat.yml bro
  template:
    src: 'conf/filebeat/bro.yml'
    dest: '/etc/filebeat/conf.d/bro.yml'
    owner: root
    group: root
    mode: 0400

- name: Start Filebeat service
  service:
    name: 'filebeat'
    state: restarted
    enabled: yes

####################################################################
# Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: "{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Set up Elasticsearch - {{ ansible_nodename }}"
    channel: "{{ slack_channel }}"
  when: slack_token is undefined
