####################################################################
# Install Rsyslog
####################################################################
- name: Add ppa:adiscon/v8-stable
  apt_repository:
    repo: ppa:adiscon/v8-stable
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install Rsyslog
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - rsyslog
    - rsyslog-relp
    - rsyslog-mmjsonparse

- name: Copy Rsyslog.conf
  template:
    src: 'conf/rsyslog_client/rsyslog.conf'
    dest: '/etc/rsyslog.conf'
    owner: root
    group: root
    mode: 0400

####################################################################
# Setup Rsyslog
####################################################################
- name: Copy rsyslog configs
  template:
    src: '{{ item }}'
    dest: '/etc/rsyslog.d/{{ item | basename }}'
    owner: root
    group: root
    mode: 0400
  with_items:
    - 'conf/rsyslog_server/50-default.conf'
    - 'conf/rsyslog_client/60-osquery.conf'

- name: Start Rsyslog client
  service:
    name: rsyslog
    state: restarted
    enabled: yes

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Rsyslog on {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None
